### ISSUE TITLE
Datasets

### ISSUE THREAD

**Issue by jock-lv** [computational-imaging/AcousticNLOS#3]
What is the meaning of the 'raw_scan' in dataset ? Is it the original measured amplitude data?

**Comment by davelindell** [comment]
Yes, 'raw_scan' is the original measured data. This is then processed using the `AcousticNLOSReconstruction.py` script. The 'scan' variable is a processed version of 'raw_scan' that collapses the measurements into a 3D volume over x, y, and time.
