### ISSUE TITLE
How to get 3D image from admm_out_data with Chimera? Can I get it directly？thanks.

### ISSUE THREAD

**Issue by jock-lv** [computational-imaging/AcousticNLOS#4]

**Comment by davelindell** [comment]
The ADMM output is saved in the numpy format, so you can't directly input that into Chimera. Instead, you can save the 3D output volume in the HDF5 format with the .cmp file extension. Then that file can be directly opened with Chimera. For instructions on using Chimera I found the [user's guide](https://www.cgl.ucsf.edu/chimera/current/docs/UsersGuide/frametut.html) and [command index](https://www.cgl.ucsf.edu/chimera/current/docs/UsersGuide/framecommand.html) to be helpful.
